-- Migración para soporte Multi-empresa
-- Fase 10: Evolución Arquitectónica

-- 1. Crear tabla empresa
CREATE TABLE empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    identificacion_fiscal VARCHAR(255) UNIQUE,
    direccion VARCHAR(255),
    telefono VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insertar empresa por defecto para migración de datos existentes
INSERT INTO empresa (nombre, identificacion_fiscal, activo) 
VALUES ('Empresa Demo/Default', '00000000-0', TRUE);

-- 3. Añadir columnas empresa_id a tablas existentes con valor por defecto 1
ALTER TABLE sede ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE empleado ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE usuario ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE dispositivo ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE turno_plantilla ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE marcacion_evento ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE marcacion_intento ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE asignacion_turno ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE asistencia_dia ADD COLUMN empresa_id BIGINT DEFAULT 1;
ALTER TABLE perfil_biometrico ADD COLUMN empresa_id BIGINT DEFAULT 1;

-- 4. Establecer las claves foráneas (Foreign Keys)
ALTER TABLE sede ADD CONSTRAINT fk_sede_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE empleado ADD CONSTRAINT fk_empleado_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE usuario ADD CONSTRAINT fk_usuario_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE dispositivo ADD CONSTRAINT fk_dispositivo_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE turno_plantilla ADD CONSTRAINT fk_turno_plantilla_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE marcacion_evento ADD CONSTRAINT fk_marcacion_evento_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE marcacion_intento ADD CONSTRAINT fk_marcacion_intento_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE asignacion_turno ADD CONSTRAINT fk_asignacion_turno_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE asistencia_dia ADD CONSTRAINT fk_asistencia_dia_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE perfil_biometrico ADD CONSTRAINT fk_perfil_biometrico_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id);

-- 5. Actualizar restricciones de unicidad
-- Removemos las antiguas (que no tenían nombre explícito, se intenta por convención o se ignora si falla)
-- En H2, si se definió como UNIQUE en el CREATE TABLE, se puede soltar así:
ALTER TABLE empleado DROP CONSTRAINT IF EXISTS UK_CODIGO_EMPLEADO;
ALTER TABLE turno_plantilla DROP CONSTRAINT IF EXISTS UK_TURNO_CODIGO;

-- 6. Crear nuevas restricciones compuestas
ALTER TABLE empleado ADD CONSTRAINT uk_empleado_codigo_empresa UNIQUE (codigo_empleado, empresa_id);
ALTER TABLE turno_plantilla ADD CONSTRAINT uk_turno_codigo_empresa UNIQUE (codigo, empresa_id);
