-- Identidad y Seguridad
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('ADMIN', 'RRHH', 'SUPERVISOR', 'EMPLEADO')),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Organización
CREATE TABLE sede (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255),
    codigo_externo VARCHAR(50),
    configuracion_json TEXT,
    version_embeddings BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dispositivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_hardware VARCHAR(100) NOT NULL UNIQUE,
    sede_id BIGINT REFERENCES sede(id),
    nombre VARCHAR(100),
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('KIOSCO', 'CAMARA', 'MOVIL')),
    estado VARCHAR(20) DEFAULT 'ACTIVO',
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_heartbeat TIMESTAMP
);

-- RRHH
CREATE TABLE empleado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT UNIQUE REFERENCES usuario(id),
    supervisor_id BIGINT REFERENCES empleado(id),
    codigo_empleado VARCHAR(50) NOT NULL UNIQUE,
    numero_documento VARCHAR(20) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    email VARCHAR(100),
    estado VARCHAR(20) DEFAULT 'ACTIVO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE empleado_sede_habilitada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleado(id),
    sede_id BIGINT NOT NULL REFERENCES sede(id),
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT uk_emp_sede_vigencia UNIQUE (empleado_id, sede_id, fecha_desde)
);
