-- Definición de Turnos (Plantillas)
CREATE TABLE turno_plantilla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    tipo_turno VARCHAR(20) NOT NULL CHECK (tipo_turno IN ('FIJO', 'FLEXIBLE', 'ABIERTO')),
    es_nocturno BOOLEAN DEFAULT FALSE,
    min_break_mins INTEGER DEFAULT 0,
    max_break_mins INTEGER DEFAULT 0,
    tolerancia_entrada_mins INTEGER DEFAULT 0,
    tolerancia_salida_mins INTEGER DEFAULT 0
);

-- Segmentos de Horario (Detalle del turno)
-- Ejemplo: Turno Partido MAÑANA (08:00-13:00) y TARDE (14:00-18:00) son dos segmentos del mismo turno_plantilla
CREATE TABLE turno_segmento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_plantilla_id BIGINT NOT NULL REFERENCES turno_plantilla(id),
    orden INTEGER NOT NULL, -- 1 para entrada inicial
    hora_entrada TIME NOT NULL,
    hora_salida TIME NOT NULL,
    dia_siguiente_salida BOOLEAN DEFAULT FALSE, -- Si la salida es al día siguiente (cruce medianoche dentro del segmento)
    tolerancia_tardanza_mins INTEGER DEFAULT 0,
    tolerancia_salida_anticipada_mins INTEGER DEFAULT 0
);

-- Asignación de Turnos a Empleados
CREATE TABLE asignacion_turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleado(id),
    turno_plantilla_id BIGINT NOT NULL REFERENCES turno_plantilla(id),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE, -- NULL = Indefinido
    dias_semana VARCHAR(50) DEFAULT 'LUN,MAR,MIE,JUE,VIE', -- Formato simple para MVP
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
