-- Eventos de Marcación (Raw Data)
CREATE TABLE marcacion_evento (
    uuid VARCHAR(36) PRIMARY KEY, -- Generado en origen (Kiosco) para idempotencia
    empleado_id BIGINT REFERENCES empleado(id), -- Puede ser NULL si no identificó
    dispositivo_id BIGINT REFERENCES dispositivo(id),
    sede_id BIGINT REFERENCES sede(id),
    timestamp_evento TIMESTAMP NOT NULL,
    timestamp_servidor TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_evento VARCHAR(20) NOT NULL CHECK (tipo_evento IN ('ENTRADA', 'SALIDA', 'INICIO_BREAK', 'FIN_BREAK', 'DESCONOCIDO')),
    metodo_verificacion VARCHAR(50) DEFAULT 'FACIAL', -- PIN, FACIAL, TARJETA
    
    -- Datos Biométricos / Evidencia
    similitud_score DOUBLE,
    liveness_score DOUBLE,
    liveness_status VARCHAR(20) CHECK (liveness_status IN ('PASSED', 'FAILED', 'UNKNOWN')),
    evidencia_foto_path VARCHAR(255), -- Ruta local o URL
    evidencia_foto_hash VARCHAR(100), -- SHA256 para validación
    
    -- Estado de pre-procesamiento
    estado_proceso VARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, PROCESADO, ERROR
    error_motivo TEXT
);

-- Asistencia Diaria (Resultado Consolidado)
CREATE TABLE asistencia_dia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleado(id),
    fecha_laboral DATE NOT NULL,
    turno_asignado_id BIGINT REFERENCES turno_plantilla(id),
    
    -- Tiempos calculados
    hora_entrada_real TIMESTAMP,
    hora_salida_real TIMESTAMP,
    mins_trabajados_reales INTEGER DEFAULT 0,
    mins_tardanza INTEGER DEFAULT 0,
    mins_salida_anticipada INTEGER DEFAULT 0,
    mins_extra_antes INTEGER DEFAULT 0,
    mins_extra_despues INTEGER DEFAULT 0,
    mins_break_tomados INTEGER DEFAULT 0,
    
    -- Estado
    estado_asistencia VARCHAR(30) NOT NULL CHECK (estado_asistencia IN ('NORMAL', 'FALTA', 'TARDANZA', 'INCOMPLETO', 'FERIADO', 'LIBRE', 'REQUIERE_REVISION')),
    incidencias TEXT,
    validado_por_supervisor BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uk_asistencia_dia_emp UNIQUE (empleado_id, fecha_laboral)
);

-- Detalle de segmentos de asistencia (para turnos partidos o múltiples entradas)
CREATE TABLE asistencia_segmento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asistencia_dia_id BIGINT NOT NULL REFERENCES asistencia_dia(id),
    turno_segmento_id BIGINT REFERENCES turno_segmento(id), -- Segmento esperado
    marcacion_entrada_uuid VARCHAR(36) REFERENCES marcacion_evento(uuid),
    marcacion_salida_uuid VARCHAR(36) REFERENCES marcacion_evento(uuid),
    estado VARCHAR(20) -- COMPLETADO, SIN_SALIDA, SIN_ENTRADA
);

-- Permisos y Excepciones
CREATE TABLE permiso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleado(id),
    solicitado_por BIGINT REFERENCES usuario(id),
    aprobado_por BIGINT REFERENCES usuario(id),
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo VARCHAR(50) NOT NULL, -- VACACIONES, MEDICO, PERSONAL
    
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    es_dia_complete BOOLEAN DEFAULT TRUE,
    motivo TEXT,
    comentario_aprobador TEXT,
    
    estado VARCHAR(20) DEFAULT 'SOLICITADO' CHECK (estado IN ('SOLICITADO', 'APROBADO', 'RECHAZADO', 'CANCELADO'))
);

-- Biometría
CREATE TABLE perfil_biometrico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleado(id),
    version BIGINT DEFAULT 1,
    activo BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paquete_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sede_id BIGINT REFERENCES sede(id), -- NULL = Global/Template
    version BIGINT NOT NULL,
    fecha_generacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    url_descarga VARCHAR(255),
    hash_paquete VARCHAR(100)
);
