-- Reglas de Asistencia (Configuración avanzada)
CREATE TABLE regla_asistencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    
    -- Alcance de la regla (Prioridad: EMPLEADO > TURNO > SEDE > GLOBAL)
    nivel_alcance VARCHAR(20) NOT NULL CHECK (nivel_alcance IN ('GLOBAL', 'SEDE', 'TURNO', 'EMPLEADO')),
    entidad_id BIGINT, -- ID de Sede, Emp o Turno según alcance. NULL para GLOBAL.
    
    -- Tolerancias (Minutos)
    tolerancia_entrada INTEGER DEFAULT 0,
    tolerancia_salida INTEGER DEFAULT 0,
    tolerancia_break INTEGER DEFAULT 0,
    
    -- Redondeos (Minutos)
    -- Ej: Redondeo 15 significa que si marca 07:53, se guarda 08:00 (si es hacia adelante)
    redondeo_entrada INTEGER DEFAULT 0,
    redondeo_salida INTEGER DEFAULT 0,
    
    -- Horas Extra
    permite_horas_extra BOOLEAN DEFAULT FALSE,
    min_mins_para_extra INTEGER DEFAULT 30, -- Mínimo tiempo para que cuente como extra
    
    activo BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar regla global predeterminada
INSERT INTO regla_asistencia (nombre, nivel_alcance, tolerancia_entrada, redondeo_entrada, permite_horas_extra) 
VALUES ('REGLA GLOBAL DEFAULT', 'GLOBAL', 15, 0, TRUE);
