-- Tabla para auditar cada intento de marcación (éxitos y fracasos)
CREATE TABLE marcacion_intento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36), -- Puede ser NULL si la trama viene corrupta
    empleado_id_raw BIGINT, -- ID enviado por el cliente
    timestamp_cliente TIMESTAMP, -- Hora de la marcación en el dispositivo
    timestamp_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Hora en que se recibió en el servidor
    tipo_evento VARCHAR(50),
    metodo_verificacion VARCHAR(50),
    exito BOOLEAN DEFAULT FALSE,
    error_motivo VARCHAR(500),
    payload_original TEXT -- El toString() del DTO recibido para diagnóstico profundo
);
