server.port=8000
spring.application.name=horus-asistencia

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=temp/horus-asistencia.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

# CORS Configuration (Permite acceso local y por IP de red)
app.cors.allowed-origins=*

# Datasource Configuration (SQLite File-based for persistence, supports ENV overriding)
spring.datasource.url=${DB_URL:jdbc:sqlite:../data/horus_db.db?journal_mode=WAL&busy_timeout=5000&foreign_keys=on}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}


# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:18000000}
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Biometria Python Service
biometria.python.url=http://127.0.0.1:8001

# Configuracion Biometrica IA
# Modelos sugeridos:
# ArcFace (Umbral euclidean_l2: 1.13) - Maxima precision
# SFace (Umbral euclidean_l2: 1.055) - Maxima velocidad CPU
# IMPORTANTE: Estos umbrales son los oficiales de DeepFace para vectores L2-normalizados
horus.biometria.modelo=SFace
horus.biometria.umbral=1.055
